#.schema https://github.com/ices-tools-dev/echoSMs/blob/main/schemas/anatomical_data_store/v1/anatomical_data_store.json
uuid = ""  # populated by the data storage system
dataset_uuid = "75f775f9-4404-448d-aacc-6de96cccaf3a"
version_number = 1  # overwritten by data storage system
version_time = ""  # overwritten by data storage system
version_note = "Initial version"
version_investigators = ["Clarence Clay", "John Horne"]
description = ["Organisms used in Clay & Horne 1994 paper",]
anatomical_category = "organism"
aphia_id = 126436
class = "Teleostei"
order = "Gadiformes"
family = "Gadidae"
genus = "Gadus"
species = "Gadus morhua"
vernacular_names = ["Atlantic cod"]
reference = "doi:10.1121/1.410245"
# activity_name = ""
# location = ""
# latitude = 
# longitude = 
# depth = 
date_collection = "1970-01-01"
date_image = "1970-01-01"
# data_collection_description = ""
# notes = []
imaging_method = "radiograph"
shape_method = "manual outline of image(s)"
shape_method_processing = "Body and swimbladder shapes manually derived from x-ray image contrast"
model_type = "KRM"
sound_speed_method = "literature"
mass_density_method = "literature"
dataset_size = 0.0  # populated by data storage system
dataset_size_units = "megabyte"

specimen_name = "D"
specimen_condition = "fresh"
smoothed = true
rotated = true
straightened = true
length = 0.380
weight = 0.544
length_type = "standard length"
length_units = "m"
weight_units = "kg"
shape_type = "outline"

[[shapes]]
anatomical_feature = "body"
boundary = "fluid-filled"
shape_units = "m"
x = [ 0.0, -0.041, -0.083, -0.124, -0.165, -0.206, -0.247, -0.29, -0.33, -0.37, -0.38,]
y = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
z = [ 0.0025, 0.0025, -0.0, 0.0075, 0.01, 0.0085, 0.007, 0.005, 0.0045, 0.004, 0.0025,]
height = [ 0.015, 0.045, 0.06, 0.075, 0.074, 0.063, 0.044, 0.03, 0.023, 0.018, 0.005,]
width = [ 0.02, 0.045, 0.057, 0.06, 0.049, 0.035, 0.023, 0.012, 0.007, 0.003, 0.001,]
mass_density = [1070]
mass_density_units = "kg/m^3"
sound_speed_compressional = [1570]
sound_speed_compressional_units = "m/s"

[[shapes]]
anatomical_feature = "swimbladder"
boundary = "pressure-release"
shape_units = "m"
x = [ -0.103, -0.125, -0.144, -0.165, -0.186, -0.206,]
y = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
z = [ 0.006, 0.009, 0.0115, 0.0145, 0.0155, 0.0175,]
height = [ 0.008, 0.014, 0.017, 0.017, 0.011, 0.0030,]
width = [ 0.011, 0.025, 0.023, 0.018, 0.014, 0.007,]
mass_density = [1.24]
mass_density_units = "kg/m^3"
sound_speed_compressional = [345]
sound_speed_compressional_units = "m/s"
